# LineaBlu Cloud Build - TEMPORARY DOCKERFILE TEST
# Testing with Dockerfile to diagnose buildpack issues

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/lineablu-legal-impact-score:$COMMIT_SHA'
      - '.'

  # Push the container image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/lineablu-legal-impact-score:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'lineablu-legal-impact-score'
      - '--image=gcr.io/$PROJECT_ID/lineablu-legal-impact-score:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'
      - '--clear-env-vars'
      - '--update-secrets=NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL:latest,NEXT_PUBLIC_SUPABASE_ANON_KEY=NEXT_PUBLIC_SUPABASE_ANON_KEY:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
